// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package recallenginefb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoolValueColumn struct {
	_tab flatbuffers.Table
}

func GetRootAsBoolValueColumn(buf []byte, offset flatbuffers.UOffsetT) *BoolValueColumn {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoolValueColumn{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoolValueColumnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoolValueColumn(buf []byte, offset flatbuffers.UOffsetT) *BoolValueColumn {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoolValueColumn{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoolValueColumnBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoolValueColumn) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoolValueColumn) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoolValueColumn) Value(j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetBool(a + flatbuffers.UOffsetT(j*1))
	}
	return false
}

func (rcv *BoolValueColumn) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoolValueColumn) MutateValue(j int, n bool) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateBool(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func BoolValueColumnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BoolValueColumnAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func BoolValueColumnStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoolValueColumnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
