// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package recallenginefb

import "strconv"

type FieldValueColumn byte

const (
	FieldValueColumnNONE                   FieldValueColumn = 0
	FieldValueColumnUInt8ValueColumn       FieldValueColumn = 1
	FieldValueColumnInt32ValueColumn       FieldValueColumn = 2
	FieldValueColumnInt64ValueColumn       FieldValueColumn = 3
	FieldValueColumnFloatValueColumn       FieldValueColumn = 4
	FieldValueColumnDoubleValueColumn      FieldValueColumn = 5
	FieldValueColumnStringValueColumn      FieldValueColumn = 6
	FieldValueColumnBoolValueColumn        FieldValueColumn = 7
	FieldValueColumnMultiInt32ValueColumn  FieldValueColumn = 8
	FieldValueColumnMultiInt64ValueColumn  FieldValueColumn = 9
	FieldValueColumnMultiFloatValueColumn  FieldValueColumn = 10
	FieldValueColumnMultiDoubleValueColumn FieldValueColumn = 11
	FieldValueColumnMultiStringValueColumn FieldValueColumn = 12
	FieldValueColumnUnknownValueColumn     FieldValueColumn = 13
)

var EnumNamesFieldValueColumn = map[FieldValueColumn]string{
	FieldValueColumnNONE:                   "NONE",
	FieldValueColumnUInt8ValueColumn:       "UInt8ValueColumn",
	FieldValueColumnInt32ValueColumn:       "Int32ValueColumn",
	FieldValueColumnInt64ValueColumn:       "Int64ValueColumn",
	FieldValueColumnFloatValueColumn:       "FloatValueColumn",
	FieldValueColumnDoubleValueColumn:      "DoubleValueColumn",
	FieldValueColumnStringValueColumn:      "StringValueColumn",
	FieldValueColumnBoolValueColumn:        "BoolValueColumn",
	FieldValueColumnMultiInt32ValueColumn:  "MultiInt32ValueColumn",
	FieldValueColumnMultiInt64ValueColumn:  "MultiInt64ValueColumn",
	FieldValueColumnMultiFloatValueColumn:  "MultiFloatValueColumn",
	FieldValueColumnMultiDoubleValueColumn: "MultiDoubleValueColumn",
	FieldValueColumnMultiStringValueColumn: "MultiStringValueColumn",
	FieldValueColumnUnknownValueColumn:     "UnknownValueColumn",
}

var EnumValuesFieldValueColumn = map[string]FieldValueColumn{
	"NONE":                   FieldValueColumnNONE,
	"UInt8ValueColumn":       FieldValueColumnUInt8ValueColumn,
	"Int32ValueColumn":       FieldValueColumnInt32ValueColumn,
	"Int64ValueColumn":       FieldValueColumnInt64ValueColumn,
	"FloatValueColumn":       FieldValueColumnFloatValueColumn,
	"DoubleValueColumn":      FieldValueColumnDoubleValueColumn,
	"StringValueColumn":      FieldValueColumnStringValueColumn,
	"BoolValueColumn":        FieldValueColumnBoolValueColumn,
	"MultiInt32ValueColumn":  FieldValueColumnMultiInt32ValueColumn,
	"MultiInt64ValueColumn":  FieldValueColumnMultiInt64ValueColumn,
	"MultiFloatValueColumn":  FieldValueColumnMultiFloatValueColumn,
	"MultiDoubleValueColumn": FieldValueColumnMultiDoubleValueColumn,
	"MultiStringValueColumn": FieldValueColumnMultiStringValueColumn,
	"UnknownValueColumn":     FieldValueColumnUnknownValueColumn,
}

func (v FieldValueColumn) String() string {
	if s, ok := EnumNamesFieldValueColumn[v]; ok {
		return s
	}
	return "FieldValueColumn(" + strconv.FormatInt(int64(v), 10) + ")"
}
